### ISSUE TITLE
Add d3 functionality for plots in posts

### ISSUE THREAD

**Issue by davidbrough1** [projectpages/project-pages#19]
Create functionality that allows users to easily create interactive plots in posts.

**Comment by tonyfast** [comment]
Whats tools are you going to use to do this?

**Comment by davidbrough1** [comment]
Python, Matlab, JSON files, and d3. Do you have any suggestions?

**Comment by tonyfast** [comment]
For raw data your best bet is to use services or software that compile down to d3 rather than building you own stuff.  In the course, I use [plot.ly](http://materials-informatics-lab.github.io/2014/09/03/Plotly-Example.html) as my medium for visualization.  It is easy to push matlab code to the service and have them do the hard work for you.  Similarly, their abstractions of data are very modular and can generate many plot types that the user may choose.

The following tools might be useful for you to check out:

### Javascript not required
- [Plot.ly](plot.ly) - A web service for creating visualizations from data
- [matlab.ly](matlab.ly) - A matlab specific plot.ly community
- [App Density](http://app.raw.densitydesign.org/) - A free application to make a few highly usable and interactive visualzations.  @bollwyvl put me on to this one.

### Javascript required
- [c3](http://c3js.org/) - If you want to make your own then c3 will get you there without having to learn object oriented svg objects.  c3 is much closer to the matlab and python semantics of making graphs.
- [knsv/mermaid](https://github.com/knsv/mermaid) - Need to make diagrams or process charts?  mermaid does with a really simple markdown flavored syntax.  Here is an [example](http://bl.ocks.org/tonyfast/048fe7eaf579769997b0).

> You can imagine making a one off browser for complicated information, but it will take you a lot of time.  Simply thinking about static visualization and web-enhanced adds value immediately. If you let that be your focus then you will learn the limits and capabilities of d3 as a tool.

**Comment by davidbrough1** [comment]
- [ ] Store the D3 plots scatter plot code in [_inclues](https://github.com/matin-hub/project-pages/tree/gh-pages/_includes) directory and create [liquid tags](http://jekyllrb.com/docs/templates/) and [yaml front](http://jekyllrb.com/docs/frontmatter/) in the [post](https://github.com/matin-hub/project-pages/blob/gh-pages/_layouts/post.html) and [slide](https://github.com/matin-hub/project-pages/blob/gh-pages/_layouts/slide.html) layouts to create a simple API for users to make D3 plots scatter plots. These tags should allow the user to select which principle components they want to display.
- [ ] Use the [Python Flickr API Toolkit](http://stuvel.eu/flickrapi) or something similar to host thumbnail images associated to datapoints for scatter plot.

**Comment by ahmetcecen** [comment]
Will be resolved along #59.
